// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejwippttdxjvgwpqvffm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqd2lwcHR0ZHhqdmd3cHF2ZmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTk4NTcsImV4cCI6MjA3MjAzNTg1N30.d3xV2-bN7_P3lkfrssjUa1hLBfJ-nCVD3g9hj_PmY_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});